// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// VotingRolls voting rolls
// swagger:model VotingRolls
type VotingRolls struct {

	// pkh
	Pkh string `json:"pkh,omitempty"`

	// rolls
	Rolls int64 `json:"rolls,omitempty"`
}

// Validate validates this voting rolls
func (m *VotingRolls) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VotingRolls) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VotingRolls) UnmarshalBinary(b []byte) error {
	var res VotingRolls
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
