// Code generated by go-swagger; DO NOT EDIT.

package voting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCurrentVotingPeriodParams creates a new GetCurrentVotingPeriodParams object
// with the default values initialized.
func NewGetCurrentVotingPeriodParams() *GetCurrentVotingPeriodParams {
	var ()
	return &GetCurrentVotingPeriodParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCurrentVotingPeriodParamsWithTimeout creates a new GetCurrentVotingPeriodParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCurrentVotingPeriodParamsWithTimeout(timeout time.Duration) *GetCurrentVotingPeriodParams {
	var ()
	return &GetCurrentVotingPeriodParams{

		timeout: timeout,
	}
}

// NewGetCurrentVotingPeriodParamsWithContext creates a new GetCurrentVotingPeriodParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCurrentVotingPeriodParamsWithContext(ctx context.Context) *GetCurrentVotingPeriodParams {
	var ()
	return &GetCurrentVotingPeriodParams{

		Context: ctx,
	}
}

// NewGetCurrentVotingPeriodParamsWithHTTPClient creates a new GetCurrentVotingPeriodParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCurrentVotingPeriodParamsWithHTTPClient(client *http.Client) *GetCurrentVotingPeriodParams {
	var ()
	return &GetCurrentVotingPeriodParams{
		HTTPClient: client,
	}
}

/*GetCurrentVotingPeriodParams contains all the parameters to send to the API endpoint
for the get current voting period operation typically these are written to a http.Request
*/
type GetCurrentVotingPeriodParams struct {

	/*Block*/
	Block string
	/*Network*/
	Network string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get current voting period params
func (o *GetCurrentVotingPeriodParams) WithTimeout(timeout time.Duration) *GetCurrentVotingPeriodParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get current voting period params
func (o *GetCurrentVotingPeriodParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get current voting period params
func (o *GetCurrentVotingPeriodParams) WithContext(ctx context.Context) *GetCurrentVotingPeriodParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get current voting period params
func (o *GetCurrentVotingPeriodParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get current voting period params
func (o *GetCurrentVotingPeriodParams) WithHTTPClient(client *http.Client) *GetCurrentVotingPeriodParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get current voting period params
func (o *GetCurrentVotingPeriodParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBlock adds the block to the get current voting period params
func (o *GetCurrentVotingPeriodParams) WithBlock(block string) *GetCurrentVotingPeriodParams {
	o.SetBlock(block)
	return o
}

// SetBlock adds the block to the get current voting period params
func (o *GetCurrentVotingPeriodParams) SetBlock(block string) {
	o.Block = block
}

// WithNetwork adds the network to the get current voting period params
func (o *GetCurrentVotingPeriodParams) WithNetwork(network string) *GetCurrentVotingPeriodParams {
	o.SetNetwork(network)
	return o
}

// SetNetwork adds the network to the get current voting period params
func (o *GetCurrentVotingPeriodParams) SetNetwork(network string) {
	o.Network = network
}

// WriteToRequest writes these params to a swagger request
func (o *GetCurrentVotingPeriodParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param block
	if err := r.SetPathParam("block", o.Block); err != nil {
		return err
	}

	// path param network
	if err := r.SetPathParam("network", o.Network); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
