// Code generated by go-swagger; DO NOT EDIT.

package voting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/everstake/teztracker/services/rpc_client/models"
)

// GetVotingRollsReader is a Reader for the GetVotingRolls structure.
type GetVotingRollsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetVotingRollsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetVotingRollsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetVotingRollsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetVotingRollsOK creates a GetVotingRollsOK with default headers values
func NewGetVotingRollsOK() *GetVotingRollsOK {
	return &GetVotingRollsOK{}
}

/*GetVotingRollsOK handles this case with default header values.

Endpoint for voting rolls
*/
type GetVotingRollsOK struct {
	Payload []*models.VotingRolls
}

func (o *GetVotingRollsOK) Error() string {
	return fmt.Sprintf("[GET /chains/{network}/blocks/{block}/votes/listings][%d] getVotingRollsOK  %+v", 200, o.Payload)
}

func (o *GetVotingRollsOK) GetPayload() []*models.VotingRolls {
	return o.Payload
}

func (o *GetVotingRollsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetVotingRollsInternalServerError creates a GetVotingRollsInternalServerError with default headers values
func NewGetVotingRollsInternalServerError() *GetVotingRollsInternalServerError {
	return &GetVotingRollsInternalServerError{}
}

/*GetVotingRollsInternalServerError handles this case with default header values.

Internal error
*/
type GetVotingRollsInternalServerError struct {
}

func (o *GetVotingRollsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /chains/{network}/blocks/{block}/votes/listings][%d] getVotingRollsInternalServerError ", 500)
}

func (o *GetVotingRollsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
