// Code generated by go-swagger; DO NOT EDIT.

package voting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new voting API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for voting API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetCurrentVotingPeriod get current voting period API
*/
func (a *Client) GetCurrentVotingPeriod(params *GetCurrentVotingPeriodParams) (*GetCurrentVotingPeriodOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetCurrentVotingPeriodParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getCurrentVotingPeriod",
		Method:             "GET",
		PathPattern:        "/chains/{network}/blocks/{block}/votes/current_period_kind",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetCurrentVotingPeriodReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetCurrentVotingPeriodOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getCurrentVotingPeriod: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetVotingRolls get voting rolls API
*/
func (a *Client) GetVotingRolls(params *GetVotingRollsParams) (*GetVotingRollsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetVotingRollsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getVotingRolls",
		Method:             "GET",
		PathPattern:        "/chains/{network}/blocks/{block}/votes/listings",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetVotingRollsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetVotingRollsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getVotingRolls: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
