// Code generated by go-swagger; DO NOT EDIT.

package baking_rights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new baking rights API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for baking rights API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetBakingRights get baking rights API
*/
func (a *Client) GetBakingRights(params *GetBakingRightsParams) (*GetBakingRightsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetBakingRightsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getBakingRights",
		Method:             "GET",
		PathPattern:        "/chains/{network}/blocks/{block}/helpers/baking_rights",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetBakingRightsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetBakingRightsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getBakingRights: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
