// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetBlockOperationsParams creates a new GetBlockOperationsParams object
// with the default values initialized.
func NewGetBlockOperationsParams() *GetBlockOperationsParams {
	var ()
	return &GetBlockOperationsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetBlockOperationsParamsWithTimeout creates a new GetBlockOperationsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetBlockOperationsParamsWithTimeout(timeout time.Duration) *GetBlockOperationsParams {
	var ()
	return &GetBlockOperationsParams{

		timeout: timeout,
	}
}

// NewGetBlockOperationsParamsWithContext creates a new GetBlockOperationsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetBlockOperationsParamsWithContext(ctx context.Context) *GetBlockOperationsParams {
	var ()
	return &GetBlockOperationsParams{

		Context: ctx,
	}
}

// NewGetBlockOperationsParamsWithHTTPClient creates a new GetBlockOperationsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetBlockOperationsParamsWithHTTPClient(client *http.Client) *GetBlockOperationsParams {
	var ()
	return &GetBlockOperationsParams{
		HTTPClient: client,
	}
}

/*GetBlockOperationsParams contains all the parameters to send to the API endpoint
for the get block operations operation typically these are written to a http.Request
*/
type GetBlockOperationsParams struct {

	/*Block*/
	Block string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get block operations params
func (o *GetBlockOperationsParams) WithTimeout(timeout time.Duration) *GetBlockOperationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get block operations params
func (o *GetBlockOperationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get block operations params
func (o *GetBlockOperationsParams) WithContext(ctx context.Context) *GetBlockOperationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get block operations params
func (o *GetBlockOperationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get block operations params
func (o *GetBlockOperationsParams) WithHTTPClient(client *http.Client) *GetBlockOperationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get block operations params
func (o *GetBlockOperationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBlock adds the block to the get block operations params
func (o *GetBlockOperationsParams) WithBlock(block string) *GetBlockOperationsParams {
	o.SetBlock(block)
	return o
}

// SetBlock adds the block to the get block operations params
func (o *GetBlockOperationsParams) SetBlock(block string) {
	o.Block = block
}

// WriteToRequest writes these params to a swagger request
func (o *GetBlockOperationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param block
	if err := r.SetPathParam("block", o.Block); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
