// Code generated by go-swagger; DO NOT EDIT.

package snapshots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetRollSnapshotReader is a Reader for the GetRollSnapshot structure.
type GetRollSnapshotReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRollSnapshotReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRollSnapshotOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetRollSnapshotInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetRollSnapshotOK creates a GetRollSnapshotOK with default headers values
func NewGetRollSnapshotOK() *GetRollSnapshotOK {
	return &GetRollSnapshotOK{}
}

/*GetRollSnapshotOK handles this case with default header values.

Endpoint for snapshot number
*/
type GetRollSnapshotOK struct {
	Payload int64
}

func (o *GetRollSnapshotOK) Error() string {
	return fmt.Sprintf("[GET /chains/{network}/blocks/{block}/context/raw/json/cycle/{cycle}/roll_snapshot][%d] getRollSnapshotOK  %+v", 200, o.Payload)
}

func (o *GetRollSnapshotOK) GetPayload() int64 {
	return o.Payload
}

func (o *GetRollSnapshotOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRollSnapshotInternalServerError creates a GetRollSnapshotInternalServerError with default headers values
func NewGetRollSnapshotInternalServerError() *GetRollSnapshotInternalServerError {
	return &GetRollSnapshotInternalServerError{}
}

/*GetRollSnapshotInternalServerError handles this case with default header values.

Internal error
*/
type GetRollSnapshotInternalServerError struct {
}

func (o *GetRollSnapshotInternalServerError) Error() string {
	return fmt.Sprintf("[GET /chains/{network}/blocks/{block}/context/raw/json/cycle/{cycle}/roll_snapshot][%d] getRollSnapshotInternalServerError ", 500)
}

func (o *GetRollSnapshotInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
