// Code generated by go-swagger; DO NOT EDIT.

package snapshots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetRollsReader is a Reader for the GetRolls structure.
type GetRollsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRollsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRollsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetRollsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetRollsOK creates a GetRollsOK with default headers values
func NewGetRollsOK() *GetRollsOK {
	return &GetRollsOK{}
}

/*GetRollsOK handles this case with default header values.

Endpoint for rolls
*/
type GetRollsOK struct {
	Payload []int64
}

func (o *GetRollsOK) Error() string {
	return fmt.Sprintf("[GET /chains/{network}/blocks/{block}/context/raw/json/rolls/owner/snapshot/{cycle}/{snap}][%d] getRollsOK  %+v", 200, o.Payload)
}

func (o *GetRollsOK) GetPayload() []int64 {
	return o.Payload
}

func (o *GetRollsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRollsInternalServerError creates a GetRollsInternalServerError with default headers values
func NewGetRollsInternalServerError() *GetRollsInternalServerError {
	return &GetRollsInternalServerError{}
}

/*GetRollsInternalServerError handles this case with default header values.

Internal error
*/
type GetRollsInternalServerError struct {
}

func (o *GetRollsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /chains/{network}/blocks/{block}/context/raw/json/rolls/owner/snapshot/{cycle}/{snap}][%d] getRollsInternalServerError ", 500)
}

func (o *GetRollsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
