// Code generated by go-swagger; DO NOT EDIT.

package snapshots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRollSnapshotParams creates a new GetRollSnapshotParams object
// with the default values initialized.
func NewGetRollSnapshotParams() *GetRollSnapshotParams {
	var ()
	return &GetRollSnapshotParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRollSnapshotParamsWithTimeout creates a new GetRollSnapshotParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRollSnapshotParamsWithTimeout(timeout time.Duration) *GetRollSnapshotParams {
	var ()
	return &GetRollSnapshotParams{

		timeout: timeout,
	}
}

// NewGetRollSnapshotParamsWithContext creates a new GetRollSnapshotParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRollSnapshotParamsWithContext(ctx context.Context) *GetRollSnapshotParams {
	var ()
	return &GetRollSnapshotParams{

		Context: ctx,
	}
}

// NewGetRollSnapshotParamsWithHTTPClient creates a new GetRollSnapshotParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRollSnapshotParamsWithHTTPClient(client *http.Client) *GetRollSnapshotParams {
	var ()
	return &GetRollSnapshotParams{
		HTTPClient: client,
	}
}

/*GetRollSnapshotParams contains all the parameters to send to the API endpoint
for the get roll snapshot operation typically these are written to a http.Request
*/
type GetRollSnapshotParams struct {

	/*Block*/
	Block string
	/*Cycle*/
	Cycle int64
	/*Network*/
	Network string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get roll snapshot params
func (o *GetRollSnapshotParams) WithTimeout(timeout time.Duration) *GetRollSnapshotParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get roll snapshot params
func (o *GetRollSnapshotParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get roll snapshot params
func (o *GetRollSnapshotParams) WithContext(ctx context.Context) *GetRollSnapshotParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get roll snapshot params
func (o *GetRollSnapshotParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get roll snapshot params
func (o *GetRollSnapshotParams) WithHTTPClient(client *http.Client) *GetRollSnapshotParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get roll snapshot params
func (o *GetRollSnapshotParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBlock adds the block to the get roll snapshot params
func (o *GetRollSnapshotParams) WithBlock(block string) *GetRollSnapshotParams {
	o.SetBlock(block)
	return o
}

// SetBlock adds the block to the get roll snapshot params
func (o *GetRollSnapshotParams) SetBlock(block string) {
	o.Block = block
}

// WithCycle adds the cycle to the get roll snapshot params
func (o *GetRollSnapshotParams) WithCycle(cycle int64) *GetRollSnapshotParams {
	o.SetCycle(cycle)
	return o
}

// SetCycle adds the cycle to the get roll snapshot params
func (o *GetRollSnapshotParams) SetCycle(cycle int64) {
	o.Cycle = cycle
}

// WithNetwork adds the network to the get roll snapshot params
func (o *GetRollSnapshotParams) WithNetwork(network string) *GetRollSnapshotParams {
	o.SetNetwork(network)
	return o
}

// SetNetwork adds the network to the get roll snapshot params
func (o *GetRollSnapshotParams) SetNetwork(network string) {
	o.Network = network
}

// WriteToRequest writes these params to a swagger request
func (o *GetRollSnapshotParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param block
	if err := r.SetPathParam("block", o.Block); err != nil {
		return err
	}

	// path param cycle
	if err := r.SetPathParam("cycle", swag.FormatInt64(o.Cycle)); err != nil {
		return err
	}

	// path param network
	if err := r.SetPathParam("network", o.Network); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
