// Code generated by go-swagger; DO NOT EDIT.

package endorsing_rights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/everstake/teztracker/services/rpc_client/models"
)

// GetEndorsingRightsReader is a Reader for the GetEndorsingRights structure.
type GetEndorsingRightsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetEndorsingRightsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetEndorsingRightsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetEndorsingRightsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetEndorsingRightsOK creates a GetEndorsingRightsOK with default headers values
func NewGetEndorsingRightsOK() *GetEndorsingRightsOK {
	return &GetEndorsingRightsOK{}
}

/*GetEndorsingRightsOK handles this case with default header values.

Query compatibility endpoint for account
*/
type GetEndorsingRightsOK struct {
	Payload []*models.EndorsementRight
}

func (o *GetEndorsingRightsOK) Error() string {
	return fmt.Sprintf("[GET /chains/{network}/blocks/{block}/helpers/endorsing_rights][%d] getEndorsingRightsOK  %+v", 200, o.Payload)
}

func (o *GetEndorsingRightsOK) GetPayload() []*models.EndorsementRight {
	return o.Payload
}

func (o *GetEndorsingRightsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetEndorsingRightsInternalServerError creates a GetEndorsingRightsInternalServerError with default headers values
func NewGetEndorsingRightsInternalServerError() *GetEndorsingRightsInternalServerError {
	return &GetEndorsingRightsInternalServerError{}
}

/*GetEndorsingRightsInternalServerError handles this case with default header values.

Internal error
*/
type GetEndorsingRightsInternalServerError struct {
}

func (o *GetEndorsingRightsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /chains/{network}/blocks/{block}/helpers/endorsing_rights][%d] getEndorsingRightsInternalServerError ", 500)
}

func (o *GetEndorsingRightsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
